/**
 * This code was generated by Builder.io.
 */
import { Component, OnInit } from "@angular/core";
import { ProgressBarComponent } from "./progress-bar/progress-bar.component";
import { HeaderComponent } from "./header/header.component";
import { UserInfoComponent } from "./user-info/user-info.component";
import { SummaryComponent } from "./summary/summary.component";

@Component({
  selector: "app-receiver-details",
  
  templateUrl: "./receiver-details.component.html",
  styleUrls: ["./receiver-details.component.css"],
})
export class ReceiverDetailsComponent implements OnInit {
  currentStep: number = 3;
  totalSteps: number = 7;

  constructor() {}

  ngOnInit(): void {}

  onBack(): void {}

  onContinue(): void {}
}
