/**
 * This code was generated by Builder.io.
 */
import { NgModule } from "@angular/core";
import { CommonModule } from "@angular/common";
import { ReactiveFormsModule } from "@angular/forms";
import { ReceiverDetailsComponent } from "./receiver-details.component";
import { HeaderComponent } from "./header/header.component";
import { UserInfoComponent } from "./user-info/user-info.component";
import { ProgressBarComponent } from "./progress-bar/progress-bar.component";
import { ReceiverFormComponent } from "./receiver-form/receiver-form.component";
import { SummaryComponent } from "./summary/summary.component";
import { RouterModule, Routes } from "@angular/router";


const routes: Routes = [{ path: "", component: ReceiverFormComponent }];

@NgModule({
  declarations: [
    
  ],
  imports: [CommonModule, ReactiveFormsModule,  RouterModule.forChild(routes)], 
  exports: [],
})
export class ReceiverDetailsModule {}
