/**
 * This code was generated by Builder.io.
 */
import { NgModule } from "@angular/core";
import { RouterModule, Routes } from "@angular/router";
import { ReceiverDetailsComponent } from "./receiver-details.component";
import { CommonModule } from "@angular/common";

const routes: Routes = [{ path: "", component: ReceiverDetailsComponent }];

@NgModule({
  imports: [CommonModule, RouterModule.forChild(routes)],
  exports: [],
  declarations: [ReceiverDetailsComponent], // Make sure the component is declared here

})
export class ReceiverDetailsRoutingModule {}
