/**
 * This code was generated by Builder.io.
 */
import { Component } from "@angular/core";

@Component({
  selector: "app-summary",
  templateUrl: "./summary.component.html",
  styleUrls: ["./summary.component.css"],
})
export class SummaryComponent {
  summaryData = {
    sendAmount: "100.00 USD",
    guaranteedRate: "82.750 INR",
    receiverGets: "8,270.50 INR",
    ourFees: "1.00 USD",
    promoCode: "-",
    totalAmount: "101.00 USD",
    payBy: "Cash",
    location: "-",
    receiveBy: "Cash pickup",
    available: "In minutes",
  };
}
