/**
 * This code was generated by Builder.io.
 */
import { Component } from "@angular/core";
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from "@angular/forms";
import { SummaryComponent } from "../summary/summary.component";

@Component({
  selector: "app-receiver-form",
  standalone: true,
  imports: [ReactiveFormsModule, SummaryComponent],
  templateUrl: "./receiver-form.component.html",
  styleUrls: ["./receiver-form.component.css"],
})
export class ReceiverFormComponent {
  receiverForm: FormGroup;

  constructor(private fb: FormBuilder) {
    this.receiverForm = this.fb.group({
      firstName: ["", Validators.required],
      lastName: ["", Validators.required],
      email: ["", [Validators.required, Validators.email]],
      dob: ["", Validators.required],
      countryCode: ["", Validators.required],
      mobileNumber: ["", Validators.required],
      securityQuestion: ["", Validators.required],
      securityAnswer: ["", Validators.required],
    });
  }

  onSubmit(): void {
    if (this.receiverForm.valid) {
      console.log(this.receiverForm.value);
    }
  }
}
