/**
 * This code was generated by Builder.io.
 */
import { Component, Input } from "@angular/core";

@Component({
  selector: "app-progress-bar",
  templateUrl: "./progress-bar.component.html",
  styleUrls: ["./progress-bar.component.css"],
})
export class ProgressBarComponent {
  @Input() currentStep: number = 1;
  @Input() totalSteps: number = 1;

  get progressPercentage(): number {
    return (this.currentStep / this.totalSteps) * 100;
  }

  getStepStatus(step: number): string {
    if (step < this.currentStep) return "completed";
    if (step === this.currentStep) return "active";
    return "upcoming";
  }
}
