/**
 * This code was generated by Builder.io.
 */
import { NgModule } from "@angular/core";
import { RouterModule, Routes } from "@angular/router";
import { LoginPageComponent } from "../login/login.component";

export const routes: Routes = [
  // { path: "login", component: LoginPageComponent },
  { path: "", redirectTo: "/login", pathMatch: "full" },
  
    { path: 'login', component: LoginPageComponent },
  
  {
    path: "receiver-details",
    loadChildren: () =>
      import("../receiver-details/receiver-details.module").then(
        (m) => m.ReceiverDetailsModule
      ),
  },
  { path: "**", redirectTo: "/receiver-details" },
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [],
  declarations: [],
})
export class AppRoutingModule {}
