/**
 * This code was generated by Builder.io.
 */
import { Component } from "@angular/core";
import { RouterOutlet } from "@angular/router";
import { LoginPageComponent } from "../login/login.component";

@Component({
  selector: "app-root",
  standalone: true,
  imports: [RouterOutlet],
  templateUrl: "./app.component.html",
  styles: [],
})
export class AppComponent {
  title = "receiver-details-app";
}
