/**
 * This code was generated by Builder.io.
 */
import { Component } from "@angular/core";

@Component({
  selector: "app-user-info",
  templateUrl: "./user-info.component.html",
  styleUrls: ["./user-info.component.css"],
})
export class UserInfoComponent {
  lastLogin: string = "02, Nov, 2022 | 14:02";

  onSettings(): void {}

  onLogout(): void {}
}
